name: Build and publish Latex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile paper PDF
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: paper.tex
          work_in_root_file_dir: true
      - name: Generate build artifact (PDF)
        uses: actions/upload-artifact@v4
        with:
          name: build-pdf
          path: paper.pdf

  build-html:
    runs-on: ubuntu-latest
    name: Build HTML
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile paper HTML
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make4ht -u paper.tex "mathjax,htmlex" && bibtex paper && make4ht -u paper.tex "mathjax,htmlex"
      - name: Prepare deployment artifact
        run: |
          mkdir site
          cp paper.html site/index.html
          cp paper.css site/paper.css
          cp paper.bib site/paper.bib
          cp -r img/ site/
          echo "img {max-width: 100%; height: auto;}" >> site/paper.css
          echo "table { display: block; overflow-x: auto; overflow-y: hidden; white-space: nowrap; max-width: 100%; box-sizing: border-box; }" >> site/paper.css
      - name: Generate build artifact (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: build-html
          path: site

  deploy:
    name: Deploy PDF and HTML
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-pdf, build-html]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: build-pdf
          path: site/pdf
      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: build-html
          path: site/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
